version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./_Docker/Dockerfile
    container_name: lab-log-parser
    tty: true
    command:
      - /entrypoint.sh
    volumes:
      - .:/app
    ports:
      - 30001:3000
